spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://uade-recipes-trident.database.windows.net;databaseName=RecipesUade"
    username: TridentAdmin
    password: Tridente+1
  mail:
    host: smtp.gmail.com
    port: 587
    username: tasty.hub2022@gmail.com
    password: cassjpajwurqukbl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true