spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      userName: rootuser
      password: rootpass
      database: recipes
