spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://uade-recipes-trident.database.windows.net;databaseName=RecipesUade"
    username: TridentAdmin
    password: Tridente+1
