spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:

    hibernate:
       ddl-auto: "update"
    show-sql: true
  datasource:
    url: "jdbc:sqlserver://localhost:2000;databaseName=Recipes"
    username: agustin
    password:

